@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Model as ModelPackage <<Rectangle>> {
    Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
    Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
    Class "<<interface>>\nModel" as Model
    Class AddressBook
    Class ModelManager
    Class UserPrefs

    ' domain-level collections
    Class UniqueAthleteList
    Class UniqueOrganizationList
    Class UniqueContractList

    ' domain entities
    Class Athlete
    Class Organization
    Class Contract
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

' --- hierarchy and interfaces ---
AddressBook .up.|> ReadOnlyAddressBook
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager .up.|> Model

' --- Model references ---
Model .left.> ReadOnlyAddressBook
Model .right.> ReadOnlyUserPrefs

' --- ModelManager composition ---
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs

' --- AddressBook contains all domain lists ---
AddressBook *--> "1" UniqueAthleteList
AddressBook *--> "1" UniqueOrganizationList
AddressBook *--> "1" UniqueContractList

' --- each list contains entities ---
UniqueAthleteList *--> "*" Athlete
UniqueOrganizationList *--> "*" Organization
UniqueContractList *--> "*" Contract

' --- entity relationships ---
Contract --> Athlete : references >
Contract --> Organization : references >

' --- filtered lists (observed by UI) ---
ModelManager --> "~* filtered" Athlete
ModelManager --> "~* filtered" Organization
ModelManager --> "~* filtered" Contract

' --- layout helpers ---
Athlete -[hidden]right-> Organization
Organization -[hidden]right-> Contract

@enduml
