@startuml parseDetails
!include style.puml
skinparam ArrowFontStyle plain

hide footbox

participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteAthleteCommandParser" as DeleteAthleteCommandParser LOGIC_COLOR
participant "d:DeleteAthleteCommand" as DeleteAthleteCommand LOGIC_COLOR

activate AddressBookParser
group sd parse details and build delete command
  create DeleteAthleteCommandParser
  AddressBookParser -> DeleteAthleteCommandParser
  activate DeleteAthleteCommandParser


  DeleteAthleteCommandParser --> AddressBookParser
  deactivate DeleteAthleteCommandParser
  destroy DeleteAthleteCommandParser

  AddressBookParser -> DeleteAthleteCommandParser : create & parse arguments

  create DeleteAthleteCommand
  DeleteAthleteCommandParser -> DeleteAthleteCommand : new(...)
  activate DeleteAthleteCommand

  DeleteAthleteCommand --> DeleteAthleteCommandParser : constructed
  deactivate DeleteAthleteCommand
  destroy DeleteAthleteCommand

  DeleteAthleteCommandParser --> AddressBookParser : parsed command
end
@enduml
